config/routes.rb
Rails.application.routes.draw do
    get "tasks", to: "tasks#index", as: :index



    get "tasks/new", to: "tasks#new", as: :new
    post "tasks", to: "tasks#create"



    get "tasks/:id/edit", to: "tasks#edit", as: :edit
    patch "tasks/:id", to: "tasks#update"

     get "tasks/:id", to: "tasks#show", as: :task

    delete "tasks/:id", to: "tasks#destroy", as: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save!
      redirect_to task_path(@task)
    else
      redirect_to new_path
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
     @task = Task.find(params[:id])
     if @task.update(task_params)
       redirect_to task_path(@task)
    else
      redirect_to index_path
    end

  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path

  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.check_box :completed%>

  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>my tasks</h1>



<% @tasks.each do |task| %>

<p><%= check_box_tag(name = 'name', value = 1, comleted = task.completed)-%>- <strong> <%= link_to  task.title, task_path(task)%></strong> <%= link_to  raw("<i class='far fa-trash-alt'></i>"), destroy_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
<% end %>

<%= link_to 'add new task', new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= link_to 'edit', edit_path %>


<h1><%= @task.title %></h1>

<%= @task.details %></p>

<%=check_box_tag '[]', @task.completed %> <%=  @task.completed ? "completed" : "not completed" %>
<br>
<br>

<%= link_to 'back to list', index_path  %>